site_url: https://switchframemedia.com
logo_url: https://switchframemedia.com/wp-content/uploads/2018/04/switchframe-media-logo-1.png
search: false
publish_mode: editorial_workflow
media_folder: "public/assets" # Location where files will be stored in the repo
public_folder: "assets" # The src attribute for uploaded media
backend:
  name: github
  branch: main
  repo: "sterlingwes/switchframe"
  base_url: https://decap.swj.io
  squash_merges: true
collections:
  - name: "clients"
    label: "Clients"
    create: false
    files:
      - label: Carousel
        name: carousel
        file: "src/content/clients/index.md"
        fields:
          - label: Carousel Logos
            name: logos
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Logo", name: "logo", widget: "image" }
              - { label: "Website", name: "website", widget: "string" }
  - name: "portfolio" # Used in routes, e.g., /admin/collections/blog
    label: "Portfolio" # Used in the UI
    folder: "src/content/portfolio"
    create: true
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Grid Image", name: "thumbnail", widget: "image" }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Videos", name: "videos", widget: "list" }
      - { label: "About This Project", name: "body", widget: "markdown" }
