site_url: https://switchframemedia.com
logo_url: https://switchframemedia.com/wp-content/uploads/2018/04/switchframe-media-logo-1.png
search: false
publish_mode: editorial_workflow
media_folder: "public/assets" # Location where files will be stored in the repo
public_folder: "/assets" # The src attribute for uploaded media
show_preview_links: false
backend:
  name: github
  branch: main
  repo: "sterlingwes/switchframe"
  base_url: https://decap.swj.io
  squash_merges: true
collections:
  - name: "clients"
    label: "Clients / Ordering"
    create: false
    files:
      - label: Carousel
        name: carousel
        file: "src/content/clients/index.md"
        editor:
          preview: false
        fields:
          - label: Carousel Logos
            name: logos
            widget: list
            fields:
              - { label: "Name", name: "name", widget: "string" }
              - { label: "Logo", name: "logo", widget: "image" }
              - { label: "Website", name: "website", widget: "string" }
      - label: Portfolio Ordering
        name: portfolio_order
        file: "src/content/clients/index-portfolio.md"
        editor:
          preview: false
        fields:
          - label: Portfolio Order
            name: order
            widget: list
            fields:
              - label: "Item"
                name: "item"
                widget: "relation"
                collection: "portfolio"
                value_field: "title"
                search_fields: ["title"]
  - name: "portfolio"
    label: "Portfolio"
    folder: "src/content/portfolio"
    create: true
    editor:
      preview: false
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Grid Image", name: "thumbnail", widget: "image" }
      - { label: "Client", name: "client", widget: "string" }
      - { label: "Categories", name: "categories", widget: "list" }
      - { label: "Videos", name: "videos", widget: "list" }
      - { label: "About This Project", name: "body", widget: "markdown" }
  - name: settings
    label: Settings
    create: false
    files:
      - label: Home Banner Video
        name: home_banner_video
        file: "src/content/settings/home-banner-vid.md"
        editor:
          preview: false
        fields:
          - label: Youtube Video ID
            name: id
            widget: string
          - label: Start (from) time
            name: start
            widget: string
          - label: End (to) time
            name: end
            widget: string
          - label: Cover Image
            name: cover
            widget: image
