name: Github Pages Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v1
        name: setup bun
        with:
          bun-version: 1.0.30

      - name: install dependencies
        run: bun install

      - uses: sterlingwes/gh-pages-deploy-action@v1.3
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          source-directory: dist
          build-command: bun run build
          auto-install: nope
