name: Github Pages Publish

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: sterlingwes/gh-pages-deploy-action@v1.2
        with:
          access-token: ${{ secrets.ACCESS_TOKEN }}
          source-directory: dist
          build-command: bun build
